// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbC_pfyS2T5DACUz42ec8H0FevMHqmKoE',
    appId: '1:806722665241:web:4c0263b14599c8ecb52388',
    messagingSenderId: '806722665241',
    projectId: 'appdevfinal-8cad0',
    authDomain: 'appdevfinal-8cad0.firebaseapp.com',
    storageBucket: 'appdevfinal-8cad0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm8XTSlIfxNZha2FHdAycbf-tVzu8LM-I',
    appId: '1:806722665241:android:c28e7458c08bd5a0b52388',
    messagingSenderId: '806722665241',
    projectId: 'appdevfinal-8cad0',
    storageBucket: 'appdevfinal-8cad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9EfLK1iCsQF1G2cjZB0KnG1e0NZ-kTp8',
    appId: '1:806722665241:ios:3d5b0e18f235654bb52388',
    messagingSenderId: '806722665241',
    projectId: 'appdevfinal-8cad0',
    storageBucket: 'appdevfinal-8cad0.firebasestorage.app',
    iosBundleId: 'com.example.appDevFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9EfLK1iCsQF1G2cjZB0KnG1e0NZ-kTp8',
    appId: '1:806722665241:ios:3d5b0e18f235654bb52388',
    messagingSenderId: '806722665241',
    projectId: 'appdevfinal-8cad0',
    storageBucket: 'appdevfinal-8cad0.firebasestorage.app',
    iosBundleId: 'com.example.appDevFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbC_pfyS2T5DACUz42ec8H0FevMHqmKoE',
    appId: '1:806722665241:web:5556a0e037ba26cab52388',
    messagingSenderId: '806722665241',
    projectId: 'appdevfinal-8cad0',
    authDomain: 'appdevfinal-8cad0.firebaseapp.com',
    storageBucket: 'appdevfinal-8cad0.firebasestorage.app',
  );
}
